// Auto-generated by test_cov. Do not edit by hand.

import 'commands/no_op_test.dart' as commands_no_op_test;
import 'commands/ping_test.dart' as commands_ping_test;
import 'commands/pong_test.dart' as commands_pong_test;
import 'commands/user/join_test.dart' as commands_user_join_test;
import 'commands/user/names_test.dart' as commands_user_names_test;
import 'commands/user/part_test.dart' as commands_user_part_test;
import 'commands/user/priv_msg_test.dart' as commands_user_priv_msg_test;
import 'tmi_test.dart' as tmi_test;

void main() {
  tmi_test.main();
  commands_ping_test.main();
  commands_pong_test.main();
  commands_no_op_test.main();
  commands_user_priv_msg_test.main();
  commands_user_names_test.main();
  commands_user_join_test.main();
  commands_user_part_test.main();
}
